### ISSUE TITLE
Quando entra em clientes, produtos ou ordem de serviço sem nenhum linha de dados no banco, ele fica como se fosse em um loop de carregar, tendo algum dado na tabela o mesmo já não o corre

### ISSUE THREAD

**Issue by eduardoege** [map-os/map-os-app-flutter#23]
![Screenshot_2024-05-06-18-45-02-764_br.com.mapos.os.mapos_app.jpg](https://github.com/map-os/map-os-app-flutter/assets/85074700/81f2b25f-088c-4628-a6be-3861b0709339)

**Comment by Fesantt** [comment]
Obrigado por reportar, ja estou trabalhando na correção 🚀💜
